// Existing Schools of Hope adapter. Reference overlay built from the Schools of
// Hope Revolving Loan Fund payment ledger (F.S. 1001.292 / FL DOE loan-fund
// page). Data file is generated by scripts/build-schools-of-hope.mjs, which
// geocodes each ledger address with the U.S. Census geocoder.

import { loadValidated } from "./base";
import type { LoadResult, SchoolsOfHopeCollection } from "../types";

export const SAMPLE_URL = "/data/schools_of_hope.json";

function validate(raw: unknown): SchoolsOfHopeCollection {
  const fc = raw as SchoolsOfHopeCollection;
  if (!fc || fc.type !== "FeatureCollection" || !Array.isArray(fc.features)) {
    throw new Error("schools_of_hope.json is not a GeoJSON FeatureCollection.");
  }
  for (const f of fc.features) {
    const c = f.geometry?.coordinates;
    if (!Array.isArray(c) || c.length !== 2 || !Number.isFinite(c[0]) || !Number.isFinite(c[1])) {
      throw new Error(`A Schools of Hope site has invalid coordinates: ${JSON.stringify(f.properties?.operator)}`);
    }
  }
  return fc;
}

export function loadSchoolsOfHope(): Promise<LoadResult<SchoolsOfHopeCollection>> {
  return loadValidated(SAMPLE_URL, validate, {
    source: "FL DOE Schools of Hope Revolving Loan Fund ledger (F.S. 1001.292)",
    vintage: "Ledger as reproduced in project resources; geocoded via U.S. Census",
  });
}
